# Change these first
owner: qiuzhenwang # Your GitHub username
repo: upptime-test # Your Github repository name

# Add your sites here
sites:
  - name: Baidu
    url: https://www.baidu.com
  - name: PeopleNews
    url: http://www.people.com.cn/
  - name: bilibili
    url: https://www.bilibili.com
  - name: Google
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: qiuzhenwang.github.io
  introTitle: "**Upptime-test**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
